--1) 과목번호, 과목이름, 과목별 평균 기말고사 성적을 갖는 커서를 만들고
--   기본 LOOP문을 이용해서 모든 과목의 과목번호, 과목이름, 과목별 평균 기말고사 성적을 출력하세요.

DECLARE

	CURSOR COURSE_CUR IS
		SELECT C.CNO
			 , C.CNAME
			 , AVG(SC.RESULT) AS AVG_RES
		FROM COURSE C
		JOIN SCORE SC
		ON SC.CNO = C.CNO
		GROUP BY C.CNO, C.CNAME;
	
	TYPE COURSE_REC IS RECORD(
		CNO COURSE.CNO%TYPE,
		CNAME COURSE.CNAME%TYPE,
		AVG_RES NUMBER
	);

	COURSEREC COURSE_REC;

BEGIN
	
	OPEN COURSE_CUR;

	LOOP
		
		FETCH COURSE_CUR INTO COURSEREC;
	
		DBMS_OUTPUT.PUT_LINE(COURSEREC.CNO);
		DBMS_OUTPUT.PUT_LINE(COURSEREC.CNAME);
		DBMS_OUTPUT.PUT_LINE(COURSEREC.AVG_RES);
	
		EXIT WHEN COURSE_CUR%NOTFOUND;
	
	END LOOP;	

	CLOSE COURSE_CUR;
END;		



--2) 학생번호, 학생이름과 학생별 평균 기말고사 성적을 갖는 테이블 T_STAVGSC를 만들고
--   커서를 이용하여 학생번호, 학생이름, 학생별 평균 기말고사 성적을 조회하고 
--   조회된 데이터를 생성한 테이블인 T_STAVGSC에 저장하세요.

CREATE TABLE T_STAVGSC(
	SNO VARCHAR2(8),
	SNAME VARCHAR2(20),
	AVR_RES NUMBER
);

DECLARE

	CURSOR STUDENT_CUR IS
		SELECT ST.SNO
			 , ST.SNAME
			 , AVG(SC.RESULT) AS AVG_RES
		FROM STUDENT ST
		JOIN SCORE SC
		ON SC.SNO = ST.SNO
		GROUP BY ST.SNO, ST.SNAME;

BEGIN

	FOR STUDENT_CUR_ROW IN STUDENT_CUR LOOP
		DBMS_OUTPUT.PUT_LINE(STUDENT_CUR_ROW.SNO);
		DBMS_OUTPUT.PUT_LINE(STUDENT_CUR_ROW.SNAME);
		DBMS_OUTPUT.PUT_LINE(STUDENT_CUR_ROW.AVG_RES);
		INSERT INTO T_STAVGSC 
		VALUES STUDENT_CUR_ROW;
		COMMIT;
		
	END LOOP;	

END;		

SELECT *
FROM T_STAVGSC;